#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_cfssl="$(cfssl version 2>/dev/null | awk '$1 == "Version:" { print $2 }' || true)"
  jq -n --arg cfssl "$ver_cfssl" '{cfssl: $cfssl}'
}

version "$@"
