#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_cfssl="0.0.1"
  jq -n --arg cfssl "$ver_cfssl" '{cfssl: $cfssl}'
}

version "$@"
